### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by spaceone** [crunchy-github/python-notifier#8]
Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-module", line 119, in <module>
    notifier.loop()
  File "/usr/lib/pymodules/python2.7/notifier/nf_generic.py", line 284, in loop
    step()
  File "/usr/lib/pymodules/python2.7/notifier/nf_generic.py", line 220, in step
    fds = __poll.poll( timeout )
OverflowError: Python int too large to convert to C long

**Comment by spaceone** [comment]
Will be fixed with PR #16
